const factList = [
    "Bananas are naturally slightly radioactive. 1 banana contains 0.1 microSievert",
    "You need 6.48 trillion bananas to equal Charnobyl radiation level",
    "You will certainly die from radiation poisoning if you are able to eat 10,000,000 bananas at once.",
    "You may witness chronic symptoms if you eat 274 bananas a day for seven years.",
    "Bananas are one of the most popular fruits in the world.",
    "Bananas are one of the oldest fruits grown by humans.",
    "The word 'banana' comes from the Arabic word 'banana', which means 'finger'.",
    "There are more than 1,000 different varieties of bananas around the world.",
    "Some varieties of bananas are edible only when cooked.",
    "Some bananas are blue or purple, instead of yellow.",
    "Bananas are relatively easy to grow and can grow in a variety of climatic conditions.",
    "In some countries, bananas are used to produce alcohol, such as banana wine.",
    "Bananas are commonly used in the diets of athletes as a quick and easy way to provide energy.",
    "Many people like to eat bananas raw, but they can also be cooked, fried or baked.",
    "Bananas can be used to make banana vinegar, which is used in Asian cuisine.",
    "Bananas can be used as a natural household cleaner.",
    "Bananas are an ingredient in many traditional dishes, such as curries with chicken and bananas, giving them a sweet and sour flavor and creamy texture.",
    "Bananas have many medicinal properties.",
    "I stole your banana! Don't belive me? Here it is : 🍌",
    "🍌🦍"
]